### ISSUE TITLE
Special attacks

### ISSUE THREAD

**Issue by jayktaylor** [weirdgloop/osrs-dps-calc#141]
### What feature would you like to see?

The calculator currently does not support using [special attacks](https://oldschool.runescape.wiki/w/Special_attacks) that have attack/damage/def roll modifiers. This would require several components:

- [ ] Enum for special attacks(?)
- [ ] Map for `Special attack` => `[Item IDs]` (maybe an object with name and description too to show on UI?)
- [ ] Special attack toggle on UI

#### Healing and restoration
> Healing and restoration weapons heal the user's health or restore their stats based on the damage dealt to their opponent.

Obviously, we're not taking into account the player's current health during the DPS calculation, but these attacks still modify rolls.

- [ ] Blood Sacrifice ([Ancient godsword](https://oldschool.runescape.wiki/w/Ancient_godsword))
- [ ] Invocate ([Eldritch nightmare staff](https://oldschool.runescape.wiki/w/Eldritch_nightmare_staff))
- [ ] Toxic Siphon ([Toxic blowpipe](https://oldschool.runescape.wiki/w/Toxic_blowpipe))
- [ ] Healing Blade ([Saradomin godsword](https://oldschool.runescape.wiki/w/Saradomin_godsword))

#### Stat-boosting
> Similar to stat-boosting potions, stat-boosting special attacks will temporarily boost skills above their current level.

- [ ] Liquefy ([Brine sabre](https://oldschool.runescape.wiki/w/Brine_sabre))
- [ ] Rampage ([Dragon battleaxe](https://oldschool.runescape.wiki/w/Dragon_battleaxe))
- [ ] Sanctuary ([Excalibur](https://oldschool.runescape.wiki/w/Excalibur))

#### Multi-target
> When used, multi-target attacks can hit multiple enemies with the same attack.

We're not handling multi-targets in the calculator, but these attacks still modify rolls.

- [ ] Shield Bash ([Dinh's bulwark](https://oldschool.runescape.wiki/w/Dinh%27s_bulwark))
- [ ] Annihilate ([Dragon crossbow](https://oldschool.runescape.wiki/w/Dragon_crossbow))
- [ ] Sweep ([Dragon halberd](https://oldschool.runescape.wiki/w/Dragon_halberd), [Crystal halberd](https://oldschool.runescape.wiki/w/Crystal_halberd))
- [ ] Chainhit ([Rune thrownaxe](https://oldschool.runescape.wiki/w/Rune_thrownaxe))

#### Stat-draining
> These attacks will drain the target's stats based on the amount of damage done.

- [ ] Energy Drain ([Abyssal whip](https://oldschool.runescape.wiki/w/Abyssal_whip))
- [ ] Condemn ([Accursed sceptre](https://oldschool.runescape.wiki/w/Accursed_sceptre))
- [ ] Warstrike ([Bandos godsword](https://oldschool.runescape.wiki/w/Bandos_godsword))
- [ ] Sunder ([Barrelchest anchor](https://oldschool.runescape.wiki/w/Barrelchest_anchor))
- [ ] Backstab ([Bone dagger](https://oldschool.runescape.wiki/w/Bone_dagger))
- [ ] Weaken ([Darklight](https://oldschool.runescape.wiki/w/Darklight), [Arclight](https://oldschool.runescape.wiki/w/Arclight))
- [ ] Snipe ([Dorgeshuun crossbow](https://oldschool.runescape.wiki/w/Dorgeshuun_crossbow))
- [ ] Sever ([Dragon scimitar](https://oldschool.runescape.wiki/w/Dragon_scimitar))
- [ ] Smash ([Dragon warhammer](https://oldschool.runescape.wiki/w/Dragon_warhammer), [Statius's warhammer](https://oldschool.runescape.wiki/w/Statius%27s_warhammer))
- [ ] Soulshot ([Seercull](https://oldschool.runescape.wiki/w/Seercull))

#### Accuracy and damage
> These attacks affect some combination of the attack roll and the damage roll, and may also include latent damage to a target.

- [ ] Penance ([Abyssal bludgeon](https://oldschool.runescape.wiki/w/Abyssal_bludgeon))
- [ ] Armadyl Eye ([Armadyl crossbow](https://oldschool.runescape.wiki/w/Armadyl_crossbow))
- [ ] The Judgement ([Armadyl godsword](https://oldschool.runescape.wiki/w/Armadyl_godsword))
- [ ] Pulsate ([Dawnbringer](https://oldschool.runescape.wiki/w/Dawnbringer))
- [ ] Unleash ([Dragon hasta](https://oldschool.runescape.wiki/w/Dragon_hasta))
- [ ] Cleave ([Dragon longsword](https://oldschool.runescape.wiki/w/Dragon_longsword))
- [ ] Shatter ([Dragon mace](https://oldschool.runescape.wiki/w/Dragon_mace))
- [ ] Wild Stab ([Dragon sword](https://oldschool.runescape.wiki/w/Dragon_sword))
- [ ] Momentum Throw ([Dragon thrownaxe](https://oldschool.runescape.wiki/w/Dragon_thrownaxe))
- [ ] Hammer Blow ([Granite hammer](https://oldschool.runescape.wiki/w/Granite_hammer))
- [ ] Wrath of Amascut ([Keris partisan of corruption](https://oldschool.runescape.wiki/w/Keris_partisan_of_corruption))
- [ ] Concentrated Shot ([Light ballista](https://oldschool.runescape.wiki/w/Light_ballista), [Heavy ballista](https://oldschool.runescape.wiki/w/Heavy_ballista))
- [ ] Powershot ([Magic longbow](https://oldschool.runescape.wiki/w/Magic_longbow), [Magic comp bow](https://oldschool.runescape.wiki/w/Magic_comp_bow))
- [ ] Phantom Strike ([Morrigan's javelin](https://oldschool.runescape.wiki/w/Morrigan%27s_javelin))
- [ ] Eviscerate ([Osmumten's fang](https://oldschool.runescape.wiki/w/Osmumten%27s_fang))
- [ ] Impale ([Rune claws](https://oldschool.runescape.wiki/w/Rune_claws))
- [ ] Saradomin's Blessed Lightning ([Saradomin's blessed sword](https://oldschool.runescape.wiki/w/Saradomin%27s_blessed_sword))
- [ ] Feint ([Vesta's longsword](https://oldschool.runescape.wiki/w/Vesta%27s_longsword), [Vesta's blighted longsword](https://oldschool.runescape.wiki/w/Vesta%27s_blighted_longsword).pngVesta's blighted longsword)
- [ ] Disrupt ([Voidwaker](https://oldschool.runescape.wiki/w/Voidwaker))
- [ ] Immolate ([Volatile nightmare staff](https://oldschool.runescape.wiki/w/Volatile_nightmare_staff))
- [ ] Evoke ([Zaryte crossbow](https://oldschool.runescape.wiki/w/Zaryte_crossbow))

#### Multi-hit
> These attacks hit the target multiple times in one attack or game tick.

- [ ] Abyssal Puncture ([Abyssal dagger](https://oldschool.runescape.wiki/w/Abyssal_dagger))
- [ ] Dark Bow ([Dark bow](https://oldschool.runescape.wiki/w/Dark_bow))
- [ ] Slice and Dice ([Dragon claws](https://oldschool.runescape.wiki/w/Dragon_claws))
- [ ] Puncture ([Dragon dagger](https://oldschool.runescape.wiki/w/Dragon_dagger))
- [ ] Duality ([Dragon knife](https://oldschool.runescape.wiki/w/Dragon_knife))
- [ ] Quick Smash ([Granite maul](https://oldschool.runescape.wiki/w/Granite_maul))
- [ ] Snapshot ([Magic shortbow](https://oldschool.runescape.wiki/w/Magic_shortbow))
- [ ] Saradomin's Lightning ([Saradomin sword](https://oldschool.runescape.wiki/w/Saradomin_sword))
- [ ] Swarm ([Webweaver bow](https://oldschool.runescape.wiki/w/Webweaver_bow))

#### Binding
> These attacks freeze or stun the target, holding them in place for a set amount of time. 

We probably don't really care about the stun aspect here, but these attacks still modify rolls.

- [ ] Binding Tentacle ([Abyssal tentacle](https://oldschool.runescape.wiki/w/Abyssal_tentacle))
- [ ] Bear Down ([Ursine chainmace](https://oldschool.runescape.wiki/w/Ursine_chainmace))
- [ ] Ice Cleave ([Zamorak godsword](https://oldschool.runescape.wiki/w/Zamorak_godsword))

**Comment by jayktaylor** [comment]
Initial set of spec support released in https://github.com/weirdgloop/osrs-dps-calc/releases/tag/09-07-24
