### ISSUE TITLE
NPC-vs-player damage

### ISSUE THREAD

**Issue by leejt** [weirdgloop/osrs-dps-calc#186]
### What feature would you like to see?

Compute NPC-on-offense vs player-on-defense combat.

Extremely hard to do in general because we don't understand boss attack mechanics very well, but probably can get useful answers for about 80% of monsters without all that much effort

Hard parts:

- How to make it extremely clear that it won't work very well for "complicated" monsters?
- Which metrics (DPS, max hit, total damage taken, etc) do we display in the output section? Presumably all are fair game for graph y-axis
- Getting protection prayers right would go a long way (but do we want these in the prayer UI?)
- General UI bloat for defensive-minded inputs could get to be frustrating when they are irrelevant for ~95% of users

Discussed in some detail [here](https://www.reddit.com/r/2007scape/comments/1adam6c/osrs_wiki_has_a_dps_calculator_now_go_check_it_out/kjzphhp/)

**Comment by SuperNerdEric** [comment]
Some more special cases to consider. Some of these depend on more complex things being implemented first.

- [ ] [Staff of the dead](https://oldschool.runescape.wiki/w/Staff_of_the_dead#Special_attack) / Toxic staff of the dead / Staff of balance / Staff of light special attack halves all of the opponent's melee damage
- [ ] [Insulated boots](https://oldschool.runescape.wiki/w/Insulated_boots) reduce damage from Killerwatts and Rune dragons
- [ ] [Witchwood icon](https://oldschool.runescape.wiki/w/Witchwood_icon)- The special scream attack from cave horrors is guaranteed to deal 10% of the player's total [Hitpoints](https://oldschool.runescape.wiki/w/Hitpoints) in damage when the icon is not worn. The icon does not negate all damage from the scream, it instead causes the scream attack to roll as a regular attack.
- [ ] Aberrant spectre - nose peg / slayer helm
- [ ] Sourhogs - Reinforced goggles / slayer helm
- [ ] Earmuffs - used to protect against [banshees](https://oldschool.runescape.wiki/w/Banshee)' screams and to reduce damage from [warped terrorbirds](https://oldschool.runescape.wiki/w/Warped_terrorbird) (unclear how much?)
- [ ] Wall beast - Spiny helmet
- [ ] Fever spider - Slayer gloves
- [ ] Facemask - Dust devil

**Comment by SuperNerdEric** [comment]
On warped terrorbirds
https://twitter.com/JagexAsh/status/1754800191910072403
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/cf9aa347-71c9-4551-83cd-f4c654bda999)

**Comment by SuperNerdEric** [comment]
Not sure if this was well known about dragons:
https://twitter.com/JagexAsh/status/1755605769029075288
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/f72ae578-c3ac-4dda-9fc1-1c7f6d6ade5b)
